In [ ]:
from glob import glob
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from keras.src.layers import Rescaling
from tensorflow.keras.layers import Dense, Dropout, Flatten, Conv2D
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from keras import Input
from keras.src.optimizers import Adam
from sklearn.metrics import ConfusionMatrixDisplay, classification_report
from keras.src.metrics.metrics_utils import confusion_matrix
from sklearn.metrics import precision_score, recall_score


fashion_path_train = glob("../Fashion_MNIST/fashion-mnist_train.csv")
fashion_path_test = glob("../Fashion_MNIST/fashion-mnist_test.csv")
# fish_path
fashion_data_train_ = pd.read_csv(fashion_path_train[0])
fashion_data_test_ = pd.read_csv(fashion_path_test[0])

# fashion_data_train_.shape
# fashion_data_test_.shape

# fashion_data_train_.isnull().sum().sum()
# fashion_data_train_.isna().sum().sum()
# fashion_data_test_.isnull().sum().sum()
# fashion_data_test_.isna().sum().sum()

### Preprocessing

In [ ]:
# from sklearn.preprocessing import StandardScaler

X_train = fashion_data_train_.drop(['label'], axis = 1)
X_test = fashion_data_test_.drop(['label'], axis = 1)
y_train = fashion_data_train_["label"]
y_test = fashion_data_test_["label"]

y_train_cat = keras.utils.to_categorical(y_train, num_classes=10)
y_test_cat  = keras.utils.to_categorical(y_test,  num_classes=10)

### Model Dense, Compile, Train, Predict

In [31]:
model = Sequential([
    Input(shape=(784,)),
    Rescaling(1./255),
    Dense(64, activation='relu'),
    Dense(64, activation='relu'),
    Dense(10, activation='softmax')
])


model.compile(optimizer=Adam(learning_rate=0.001), loss='categorical_crossentropy')


model.fit(X_train, y_train_cat, epochs=30, batch_size=32, validation_split=0.1)

model.evaluate(X_test, y_test_cat)

y_predi = model.predict(X_test)

y_pred = np.argmax(y_predi, axis=1)

y_pred

Epoch 1/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 2s 439us/step - loss: 0.5313 - val_loss: 0.4058
Epoch 2/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 391us/step - loss: 0.3855 - val_loss: 0.3756
Epoch 3/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 385us/step - loss: 0.3483 - val_loss: 0.3739
Epoch 4/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 385us/step - loss: 0.3270 - val_loss: 0.3493
Epoch 5/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 386us/step - loss: 0.3110 - val_loss: 0.3502
Epoch 6/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 386us/step - loss: 0.2998 - val_loss: 0.3387
Epoch 7/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 385us/step - loss: 0.2884 - val_loss: 0.3473
Epoch 8/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 390us/step - loss: 0.2763 - val_loss: 0.3527
Epoch 9/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 390us/step - loss: 0.2698 - val_loss: 0.3280
Epoch 10/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 383us/step - loss: 0.2607 - val_loss: 0.3379
Epoch 11/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 384us/step - loss: 0.2528 - val_loss: 0.3565
Epoch 12/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 384us/step - loss: 0.2467 - val_loss: 0.3388
Epoch 13/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 383us/step - loss: 0.2391 - val_loss: 0.3358
Epoch 14/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 389us/step - loss: 0.2325 - val_loss: 0.3493
Epoch 15/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 394us/step - loss: 0.2280 - val_loss: 0.3480
Epoch 16/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 434us/step - loss: 0.2243 - val_loss: 0.3225
Epoch 17/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 444us/step - loss: 0.2187 - val_loss: 0.3417
Epoch 18/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 628us/step - loss: 0.2126 - val_loss: 0.3637
Epoch 19/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 2s 931us/step - loss: 0.2091 - val_loss: 0.3409
Epoch 20/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 835us/step - loss: 0.2034 - val_loss: 0.3436
Epoch 21/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 865us/step - loss: 0.2005 - val_loss: 0.3643
Epoch 22/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 874us/step - loss: 0.1942 - val_loss: 0.3547
Epoch 23/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 814us/step - loss: 0.1915 - val_loss: 0.3670
Epoch 24/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 423us/step - loss: 0.1874 - val_loss: 0.3564
Epoch 25/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 378us/step - loss: 0.1840 - val_loss: 0.3644
Epoch 26/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 381us/step - loss: 0.1801 - val_loss: 0.3694
Epoch 27/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 385us/step - loss: 0.1787 - val_loss: 0.3855
Epoch 28/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 377us/step - loss: 0.1734 - val_loss: 0.3692
Epoch 29/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 380us/step - loss: 0.1712 - val_loss: 0.3761
Epoch 30/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 381us/step - loss: 0.1701 - val_loss: 0.3877
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 239us/step - loss: 0.3635
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 225us/step

array([0, 1, 2, ..., 8, 8, 1], shape=(10000,))

In [ ]:
print(y_pred)
print(y_test)

In [32]:
confusion_m = confusion_matrix(y_test, y_pred, num_classes=10)

precision = precision_score(y_test, y_pred, average="macro")
recall    = recall_score(y_test, y_pred, average="macro")

print("Precision :", precision)
print("Recall    :", recall)


print(f" CONFUSION MATRIX : \n {confusion_m}")
print(f" \n CLASSIFICATION REPORT : \n {classification_report(y_test, y_pred)}")

Precision : 0.8909301083746437
Recall    : 0.8897
 CONFUSION MATRIX :
 [[876   2  12  14   1   0  85   0  10   0]
 [  5 987   0   7   0   1   0   0   0   0]
 [ 27   1 769  14 130   0  58   0   1   0]
 [ 35  14   5 897  33   0  14   0   2   0]
 [  2   1  49  21 898   0  27   0   2   0]
 [  2   0   0   1   0 956   0  27   4  10]
 [172   2  58  24  93   0 643   0   8   0]
 [  0   0   0   0   0  17   0 961   0  22]
 [  5   0   3   3   6   1   9   1 972   0]
 [  1   0   0   0   0   3   0  57   1 938]]

 CLASSIFICATION REPORT :
               precision    recall  f1-score   support

           0       0.78      0.88      0.82      1000
           1       0.98      0.99      0.98      1000
           2       0.86      0.77      0.81      1000
           3       0.91      0.90      0.91      1000
           4       0.77      0.90      0.83      1000
           5       0.98      0.96      0.97      1000
           6       0.77      0.64      0.70      1000
           7       0.92      0.96      0.94      1000
           8       0.97      0.97      0.97      1000
           9       0.97      0.94      0.95      1000

    accuracy                           0.89     10000
   macro avg       0.89      0.89      0.89     10000
weighted avg       0.89      0.89      0.89     10000

## Test de plusieurs paramètres

### Model A

In [24]:
epochs = [30, 40, 50, 60, 70]

neurons = [32, 64, 128, 256, 512]

In [25]:
precisions_A = {}
all_precisions_A = {}

for neuron in neurons:
    for epoch in epochs:
        model_A = Sequential([
            Input(shape=(784,)),
            Rescaling(1./255),
            Dense(neuron, activation="relu"),
            Dense(neuron, activation="relu"),
            Dense(10, activation="softmax")
        ])

        model_A.compile(optimizer=Adam(learning_rate=0.001), loss='categorical_crossentropy')

        model_A.fit(X_train, y_train_cat, epochs=epoch, batch_size=32, validation_split=0.1)

        model_A.evaluate(X_test, y_test_cat)

        y_predi_A = model_A.predict(X_test)

        y_pred_A = np.argmax(y_predi_A, axis=1)

        precisions_A[epoch] = precision_score(y_test, y_pred_A, average="macro")

    all_precisions_A[neuron] = precisions_A
    precisions_A = {}

Epoch 1/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 366us/step - loss: 0.5638 - val_loss: 0.4790
Epoch 2/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 324us/step - loss: 0.4136 - val_loss: 0.4049
Epoch 3/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 325us/step - loss: 0.3800 - val_loss: 0.3843
Epoch 4/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.3578 - val_loss: 0.4279
Epoch 5/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 321us/step - loss: 0.3425 - val_loss: 0.3726
Epoch 6/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 321us/step - loss: 0.3269 - val_loss: 0.3601
Epoch 7/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 327us/step - loss: 0.3185 - val_loss: 0.3602
Epoch 8/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 321us/step - loss: 0.3084 - val_loss: 0.3843
Epoch 9/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 322us/step - loss: 0.3017 - val_loss: 0.3438
Epoch 10/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 321us/step - loss: 0.2948 - val_loss: 0.3432
Epoch 11/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.2905 - val_loss: 0.3477
Epoch 12/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 321us/step - loss: 0.2837 - val_loss: 0.3437
Epoch 13/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 331us/step - loss: 0.2796 - val_loss: 0.3442
Epoch 14/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 319us/step - loss: 0.2734 - val_loss: 0.3494
Epoch 15/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 317us/step - loss: 0.2706 - val_loss: 0.3408
Epoch 16/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 314us/step - loss: 0.2640 - val_loss: 0.3414
Epoch 17/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 313us/step - loss: 0.2616 - val_loss: 0.3469
Epoch 18/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.2570 - val_loss: 0.3651
Epoch 19/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 309us/step - loss: 0.2529 - val_loss: 0.3544
Epoch 20/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.2510 - val_loss: 0.3848
Epoch 21/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.2475 - val_loss: 0.3548
Epoch 22/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.2430 - val_loss: 0.3644
Epoch 23/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 309us/step - loss: 0.2423 - val_loss: 0.3587
Epoch 24/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 310us/step - loss: 0.2374 - val_loss: 0.3643
Epoch 25/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 309us/step - loss: 0.2348 - val_loss: 0.3608
Epoch 26/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 310us/step - loss: 0.2332 - val_loss: 0.3795
Epoch 27/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 310us/step - loss: 0.2310 - val_loss: 0.3769
Epoch 28/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 309us/step - loss: 0.2275 - val_loss: 0.3757
Epoch 29/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.2271 - val_loss: 0.3835
Epoch 30/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.2232 - val_loss: 0.3651
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 217us/step - loss: 0.3556
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 209us/step
Epoch 1/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 351us/step - loss: 0.5741 - val_loss: 0.4563
Epoch 2/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.4190 - val_loss: 0.4330
Epoch 3/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.3806 - val_loss: 0.4274
Epoch 4/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.3572 - val_loss: 0.3709
Epoch 5/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.3428 - val_loss: 0.3856
Epoch 6/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 314us/step - loss: 0.3318 - val_loss: 0.3914
Epoch 7/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 314us/step - loss: 0.3210 - val_loss: 0.3608
Epoch 8/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.3105 - val_loss: 0.3544
Epoch 9/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.3049 - val_loss: 0.3534
Epoch 10/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.2945 - val_loss: 0.3730
Epoch 11/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.2921 - val_loss: 0.3650
Epoch 12/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 313us/step - loss: 0.2828 - val_loss: 0.3417
Epoch 13/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 313us/step - loss: 0.2779 - val_loss: 0.3849
Epoch 14/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.2728 - val_loss: 0.3525
Epoch 15/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.2678 - val_loss: 0.3612
Epoch 16/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.2639 - val_loss: 0.3482
Epoch 17/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.2603 - val_loss: 0.3592
Epoch 18/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 313us/step - loss: 0.2538 - val_loss: 0.3573
Epoch 19/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 314us/step - loss: 0.2535 - val_loss: 0.3619
Epoch 20/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 313us/step - loss: 0.2464 - val_loss: 0.3611
Epoch 21/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 313us/step - loss: 0.2437 - val_loss: 0.3649
Epoch 22/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 313us/step - loss: 0.2398 - val_loss: 0.3514
Epoch 23/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.2397 - val_loss: 0.3584
Epoch 24/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 313us/step - loss: 0.2341 - val_loss: 0.3435
Epoch 25/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 313us/step - loss: 0.2307 - val_loss: 0.3549
Epoch 26/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 313us/step - loss: 0.2288 - val_loss: 0.3805
Epoch 27/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 313us/step - loss: 0.2267 - val_loss: 0.3879
Epoch 28/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.2258 - val_loss: 0.3593
Epoch 29/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 313us/step - loss: 0.2217 - val_loss: 0.3635
Epoch 30/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 313us/step - loss: 0.2190 - val_loss: 0.3543
Epoch 31/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 313us/step - loss: 0.2182 - val_loss: 0.3645
Epoch 32/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 313us/step - loss: 0.2152 - val_loss: 0.3707
Epoch 33/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.2131 - val_loss: 0.3604
Epoch 34/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 315us/step - loss: 0.2083 - val_loss: 0.3852
Epoch 35/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.2104 - val_loss: 0.3744
Epoch 36/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 313us/step - loss: 0.2059 - val_loss: 0.3680
Epoch 37/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.2053 - val_loss: 0.3750
Epoch 38/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 314us/step - loss: 0.2027 - val_loss: 0.3900
Epoch 39/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 313us/step - loss: 0.2023 - val_loss: 0.4031
Epoch 40/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 313us/step - loss: 0.1995 - val_loss: 0.3967
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 216us/step - loss: 0.3919
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 207us/step
Epoch 1/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 365us/step - loss: 0.5678 - val_loss: 0.4870
Epoch 2/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.4193 - val_loss: 0.4205
Epoch 3/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.3833 - val_loss: 0.3866
Epoch 4/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 313us/step - loss: 0.3612 - val_loss: 0.3834
Epoch 5/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.3466 - val_loss: 0.4040
Epoch 6/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 310us/step - loss: 0.3317 - val_loss: 0.3806
Epoch 7/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.3212 - val_loss: 0.3635
Epoch 8/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.3124 - val_loss: 0.3697
Epoch 9/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 313us/step - loss: 0.3033 - val_loss: 0.3474
Epoch 10/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.2965 - val_loss: 0.3492
Epoch 11/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.2896 - val_loss: 0.3589
Epoch 12/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.2843 - val_loss: 0.3487
Epoch 13/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.2769 - val_loss: 0.3378
Epoch 14/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.2725 - val_loss: 0.3624
Epoch 15/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.2669 - val_loss: 0.3420
Epoch 16/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.2622 - val_loss: 0.3523
Epoch 17/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 314us/step - loss: 0.2585 - val_loss: 0.3508
Epoch 18/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.2534 - val_loss: 0.3465
Epoch 19/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 310us/step - loss: 0.2526 - val_loss: 0.3409
Epoch 20/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.2458 - val_loss: 0.3429
Epoch 21/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.2439 - val_loss: 0.3633
Epoch 22/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.2409 - val_loss: 0.3524
Epoch 23/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.2369 - val_loss: 0.3571
Epoch 24/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 313us/step - loss: 0.2336 - val_loss: 0.3542
Epoch 25/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 313us/step - loss: 0.2290 - val_loss: 0.3704
Epoch 26/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 313us/step - loss: 0.2276 - val_loss: 0.3664
Epoch 27/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.2261 - val_loss: 0.3592
Epoch 28/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 313us/step - loss: 0.2238 - val_loss: 0.3623
Epoch 29/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 313us/step - loss: 0.2192 - val_loss: 0.3839
Epoch 30/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.2195 - val_loss: 0.3757
Epoch 31/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 310us/step - loss: 0.2157 - val_loss: 0.3911
Epoch 32/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 314us/step - loss: 0.2136 - val_loss: 0.4220
Epoch 33/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.2098 - val_loss: 0.3846
Epoch 34/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.2096 - val_loss: 0.3871
Epoch 35/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.2063 - val_loss: 0.3916
Epoch 36/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.2055 - val_loss: 0.3824
Epoch 37/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.2037 - val_loss: 0.3822
Epoch 38/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.1999 - val_loss: 0.4032
Epoch 39/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.2014 - val_loss: 0.4014
Epoch 40/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 315us/step - loss: 0.1974 - val_loss: 0.4008
Epoch 41/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 314us/step - loss: 0.1949 - val_loss: 0.4017
Epoch 42/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 313us/step - loss: 0.1930 - val_loss: 0.4020
Epoch 43/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.1894 - val_loss: 0.4071
Epoch 44/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 313us/step - loss: 0.1896 - val_loss: 0.4094
Epoch 45/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.1876 - val_loss: 0.4315
Epoch 46/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.1866 - val_loss: 0.4126
Epoch 47/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 310us/step - loss: 0.1856 - val_loss: 0.4178
Epoch 48/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.1842 - val_loss: 0.4294
Epoch 49/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.1828 - val_loss: 0.4245
Epoch 50/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.1820 - val_loss: 0.4378
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 218us/step - loss: 0.4103
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 212us/step
Epoch 1/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 349us/step - loss: 0.5612 - val_loss: 0.4567
Epoch 2/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 308us/step - loss: 0.4084 - val_loss: 0.4096
Epoch 3/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 309us/step - loss: 0.3761 - val_loss: 0.3864
Epoch 4/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.3527 - val_loss: 0.3739
Epoch 5/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 310us/step - loss: 0.3378 - val_loss: 0.3828
Epoch 6/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 363us/step - loss: 0.3252 - val_loss: 0.3689
Epoch 7/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 315us/step - loss: 0.3139 - val_loss: 0.3554
Epoch 8/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.3054 - val_loss: 0.3584
Epoch 9/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 310us/step - loss: 0.2959 - val_loss: 0.3527
Epoch 10/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.2884 - val_loss: 0.3432
Epoch 11/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 309us/step - loss: 0.2826 - val_loss: 0.3329
Epoch 12/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.2761 - val_loss: 0.3395
Epoch 13/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 310us/step - loss: 0.2697 - val_loss: 0.3283
Epoch 14/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.2653 - val_loss: 0.3580
Epoch 15/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 388us/step - loss: 0.2596 - val_loss: 0.3366
Epoch 16/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 310us/step - loss: 0.2578 - val_loss: 0.3417
Epoch 17/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 309us/step - loss: 0.2510 - val_loss: 0.3424
Epoch 18/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.2470 - val_loss: 0.3561
Epoch 19/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 310us/step - loss: 0.2431 - val_loss: 0.3583
Epoch 20/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 310us/step - loss: 0.2423 - val_loss: 0.3389
Epoch 21/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 309us/step - loss: 0.2353 - val_loss: 0.3361
Epoch 22/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.2354 - val_loss: 0.3398
Epoch 23/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.2298 - val_loss: 0.3505
Epoch 24/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.2272 - val_loss: 0.3434
Epoch 25/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 322us/step - loss: 0.2255 - val_loss: 0.3763
Epoch 26/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 309us/step - loss: 0.2219 - val_loss: 0.4002
Epoch 27/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 309us/step - loss: 0.2195 - val_loss: 0.3572
Epoch 28/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 309us/step - loss: 0.2187 - val_loss: 0.3737
Epoch 29/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 310us/step - loss: 0.2149 - val_loss: 0.3545
Epoch 30/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 310us/step - loss: 0.2136 - val_loss: 0.3686
Epoch 31/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.2101 - val_loss: 0.3683
Epoch 32/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 309us/step - loss: 0.2071 - val_loss: 0.3814
Epoch 33/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 309us/step - loss: 0.2086 - val_loss: 0.3958
Epoch 34/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 324us/step - loss: 0.2044 - val_loss: 0.3835
Epoch 35/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 309us/step - loss: 0.2023 - val_loss: 0.3843
Epoch 36/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 309us/step - loss: 0.2010 - val_loss: 0.3949
Epoch 37/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 308us/step - loss: 0.2005 - val_loss: 0.4003
Epoch 38/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 310us/step - loss: 0.1964 - val_loss: 0.4004
Epoch 39/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 309us/step - loss: 0.1957 - val_loss: 0.3880
Epoch 40/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 314us/step - loss: 0.1932 - val_loss: 0.3951
Epoch 41/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 309us/step - loss: 0.1925 - val_loss: 0.3869
Epoch 42/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 310us/step - loss: 0.1906 - val_loss: 0.3960
Epoch 43/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 309us/step - loss: 0.1877 - val_loss: 0.4105
Epoch 44/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 308us/step - loss: 0.1867 - val_loss: 0.4287
Epoch 45/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 308us/step - loss: 0.1863 - val_loss: 0.4332
Epoch 46/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.1840 - val_loss: 0.4072
Epoch 47/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 310us/step - loss: 0.1831 - val_loss: 0.4324
Epoch 48/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 310us/step - loss: 0.1820 - val_loss: 0.4473
Epoch 49/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 310us/step - loss: 0.1808 - val_loss: 0.4170
Epoch 50/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 310us/step - loss: 0.1789 - val_loss: 0.4238
Epoch 51/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 309us/step - loss: 0.1787 - val_loss: 0.3959
Epoch 52/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 309us/step - loss: 0.1759 - val_loss: 0.4130
Epoch 53/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 309us/step - loss: 0.1753 - val_loss: 0.4424
Epoch 54/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 309us/step - loss: 0.1730 - val_loss: 0.4110
Epoch 55/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 310us/step - loss: 0.1751 - val_loss: 0.4336
Epoch 56/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 309us/step - loss: 0.1724 - val_loss: 0.4366
Epoch 57/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 310us/step - loss: 0.1692 - val_loss: 0.4164
Epoch 58/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 310us/step - loss: 0.1679 - val_loss: 0.4403
Epoch 59/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 309us/step - loss: 0.1674 - val_loss: 0.4378
Epoch 60/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 308us/step - loss: 0.1652 - val_loss: 0.4521
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 217us/step - loss: 0.4604
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 205us/step
Epoch 1/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 351us/step - loss: 0.5584 - val_loss: 0.4643
Epoch 2/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.4135 - val_loss: 0.4641
Epoch 3/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 313us/step - loss: 0.3809 - val_loss: 0.3994
Epoch 4/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.3571 - val_loss: 0.3966
Epoch 5/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 309us/step - loss: 0.3401 - val_loss: 0.3727
Epoch 6/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.3274 - val_loss: 0.3602
Epoch 7/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 309us/step - loss: 0.3188 - val_loss: 0.3539
Epoch 8/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 308us/step - loss: 0.3067 - val_loss: 0.3507
Epoch 9/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 308us/step - loss: 0.2984 - val_loss: 0.3426
Epoch 10/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.2914 - val_loss: 0.3769
Epoch 11/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 312us/step - loss: 0.2850 - val_loss: 0.3420
Epoch 12/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 310us/step - loss: 0.2798 - val_loss: 0.3427
Epoch 13/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 310us/step - loss: 0.2737 - val_loss: 0.3752
Epoch 14/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 310us/step - loss: 0.2688 - val_loss: 0.3644
Epoch 15/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 310us/step - loss: 0.2650 - val_loss: 0.3390
Epoch 16/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 309us/step - loss: 0.2607 - val_loss: 0.3518
Epoch 17/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 309us/step - loss: 0.2575 - val_loss: 0.3669
Epoch 18/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 310us/step - loss: 0.2527 - val_loss: 0.3457
Epoch 19/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 308us/step - loss: 0.2502 - val_loss: 0.3433
Epoch 20/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 303us/step - loss: 0.2460 - val_loss: 0.3614
Epoch 21/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 304us/step - loss: 0.2423 - val_loss: 0.3480
Epoch 22/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 303us/step - loss: 0.2403 - val_loss: 0.3611
Epoch 23/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 304us/step - loss: 0.2370 - val_loss: 0.3691
Epoch 24/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 304us/step - loss: 0.2323 - val_loss: 0.3683
Epoch 25/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 305us/step - loss: 0.2322 - val_loss: 0.3526
Epoch 26/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 305us/step - loss: 0.2269 - val_loss: 0.3576
Epoch 27/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 305us/step - loss: 0.2246 - val_loss: 0.3670
Epoch 28/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 306us/step - loss: 0.2252 - val_loss: 0.3621
Epoch 29/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 306us/step - loss: 0.2208 - val_loss: 0.3597
Epoch 30/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 305us/step - loss: 0.2203 - val_loss: 0.3730
Epoch 31/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 307us/step - loss: 0.2152 - val_loss: 0.3787
Epoch 32/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 310us/step - loss: 0.2150 - val_loss: 0.3779
Epoch 33/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 310us/step - loss: 0.2133 - val_loss: 0.3895
Epoch 34/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 308us/step - loss: 0.2108 - val_loss: 0.3714
Epoch 35/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 308us/step - loss: 0.2097 - val_loss: 0.3741
Epoch 36/70

In [28]:
all_precisions_A_df = pd.DataFrame(all_precisions_A)
all_precisions_A_df

         32        64        128       256       512
30  0.882889  0.891513  0.891722  0.891108  0.897644
40  0.879738  0.892693  0.891840  0.898835  0.896746
50  0.876266  0.895133  0.893676  0.892106  0.896988
60  0.877802  0.884103  0.895776  0.893904  0.897561
70  0.885523  0.886207  0.895736  0.898479  0.889075

##### POur ce model les meilleurs paramètres sont : nbre de neurones = 256 et epochs = 40. La précision est de 0.898835

### Model B

In [26]:
precisions_B = {}
all_precisions_B = {}

for neuron in neurons:
    for epoch in epochs:
        model_B = Sequential([
            Input(shape=(784,)),
            Rescaling(1./255),
            Dense(neuron, activation="relu"),
            Dense(neuron, activation="relu"),
            Dense(neuron, activation="relu"),
            Dense(10, activation="softmax")
        ])

        model_B.compile(optimizer=Adam(learning_rate=0.001), loss='categorical_crossentropy')

        model_B.fit(X_train, y_train_cat, epochs=epoch, batch_size=32, validation_split=0.1)

        model_B.evaluate(X_test, y_test_cat)

        y_predi_B = model_B.predict(X_test)

        y_pred_B = np.argmax(y_predi_B, axis=1)

        precisions_B[epoch] = precision_score(y_test, y_pred_B, average="macro")

    all_precisions_B[neuron] = precisions_B
    precisions_B = {}

Epoch 1/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 361us/step - loss: 0.5942 - val_loss: 0.4762
Epoch 2/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 319us/step - loss: 0.4233 - val_loss: 0.4119
Epoch 3/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 319us/step - loss: 0.3836 - val_loss: 0.4026
Epoch 4/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 319us/step - loss: 0.3616 - val_loss: 0.3894
Epoch 5/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 321us/step - loss: 0.3433 - val_loss: 0.3707
Epoch 6/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 319us/step - loss: 0.3333 - val_loss: 0.3688
Epoch 7/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.3172 - val_loss: 0.3653
Epoch 8/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.3114 - val_loss: 0.3763
Epoch 9/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.3043 - val_loss: 0.3962
Epoch 10/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.2971 - val_loss: 0.3667
Epoch 11/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.2878 - val_loss: 0.3835
Epoch 12/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.2847 - val_loss: 0.3613
Epoch 13/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.2790 - val_loss: 0.3572
Epoch 14/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 317us/step - loss: 0.2732 - val_loss: 0.3488
Epoch 15/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.2691 - val_loss: 0.3528
Epoch 16/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 317us/step - loss: 0.2655 - val_loss: 0.3786
Epoch 17/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.2617 - val_loss: 0.3521
Epoch 18/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.2565 - val_loss: 0.3635
Epoch 19/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 317us/step - loss: 0.2540 - val_loss: 0.3700
Epoch 20/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 317us/step - loss: 0.2493 - val_loss: 0.3508
Epoch 21/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 317us/step - loss: 0.2447 - val_loss: 0.3681
Epoch 22/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 317us/step - loss: 0.2434 - val_loss: 0.3560
Epoch 23/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.2402 - val_loss: 0.3693
Epoch 24/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.2386 - val_loss: 0.3766
Epoch 25/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 317us/step - loss: 0.2339 - val_loss: 0.3739
Epoch 26/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 317us/step - loss: 0.2316 - val_loss: 0.3758
Epoch 27/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.2269 - val_loss: 0.3815
Epoch 28/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.2278 - val_loss: 0.3650
Epoch 29/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.2226 - val_loss: 0.3768
Epoch 30/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 317us/step - loss: 0.2210 - val_loss: 0.3840
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 216us/step - loss: 0.3455
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 209us/step
Epoch 1/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 361us/step - loss: 0.5678 - val_loss: 0.4609
Epoch 2/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 316us/step - loss: 0.4165 - val_loss: 0.4160
Epoch 3/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 325us/step - loss: 0.3821 - val_loss: 0.3971
Epoch 4/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 324us/step - loss: 0.3609 - val_loss: 0.3875
Epoch 5/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 322us/step - loss: 0.3450 - val_loss: 0.3640
Epoch 6/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 322us/step - loss: 0.3300 - val_loss: 0.3687
Epoch 7/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 322us/step - loss: 0.3200 - val_loss: 0.3561
Epoch 8/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 322us/step - loss: 0.3079 - val_loss: 0.3526
Epoch 9/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 322us/step - loss: 0.3028 - val_loss: 0.3573
Epoch 10/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 322us/step - loss: 0.2909 - val_loss: 0.3502
Epoch 11/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 322us/step - loss: 0.2866 - val_loss: 0.3556
Epoch 12/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 322us/step - loss: 0.2799 - val_loss: 0.3428
Epoch 13/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 322us/step - loss: 0.2731 - val_loss: 0.3756
Epoch 14/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 322us/step - loss: 0.2707 - val_loss: 0.3449
Epoch 15/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 322us/step - loss: 0.2643 - val_loss: 0.3640
Epoch 16/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 322us/step - loss: 0.2585 - val_loss: 0.3470
Epoch 17/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 321us/step - loss: 0.2535 - val_loss: 0.3548
Epoch 18/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 322us/step - loss: 0.2537 - val_loss: 0.3707
Epoch 19/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 322us/step - loss: 0.2487 - val_loss: 0.3540
Epoch 20/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 322us/step - loss: 0.2453 - val_loss: 0.3577
Epoch 21/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 322us/step - loss: 0.2408 - val_loss: 0.3562
Epoch 22/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 322us/step - loss: 0.2383 - val_loss: 0.3653
Epoch 23/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 322us/step - loss: 0.2353 - val_loss: 0.3409
Epoch 24/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 322us/step - loss: 0.2334 - val_loss: 0.3800
Epoch 25/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.2302 - val_loss: 0.3769
Epoch 26/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 322us/step - loss: 0.2271 - val_loss: 0.3945
Epoch 27/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 322us/step - loss: 0.2237 - val_loss: 0.3873
Epoch 28/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.2235 - val_loss: 0.3575
Epoch 29/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 324us/step - loss: 0.2180 - val_loss: 0.3822
Epoch 30/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.2166 - val_loss: 0.3758
Epoch 31/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.2147 - val_loss: 0.3689
Epoch 32/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.2127 - val_loss: 0.4126
Epoch 33/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.2092 - val_loss: 0.3785
Epoch 34/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 322us/step - loss: 0.2079 - val_loss: 0.3949
Epoch 35/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 322us/step - loss: 0.2071 - val_loss: 0.3971
Epoch 36/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 322us/step - loss: 0.2067 - val_loss: 0.3962
Epoch 37/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.2037 - val_loss: 0.3982
Epoch 38/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.2018 - val_loss: 0.4069
Epoch 39/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 324us/step - loss: 0.2009 - val_loss: 0.3942
Epoch 40/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 325us/step - loss: 0.1965 - val_loss: 0.4095
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 219us/step - loss: 0.3913
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 215us/step
Epoch 1/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 372us/step - loss: 0.5643 - val_loss: 0.4374
Epoch 2/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.4048 - val_loss: 0.3981
Epoch 3/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.3739 - val_loss: 0.4056
Epoch 4/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.3525 - val_loss: 0.3717
Epoch 5/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.3369 - val_loss: 0.3725
Epoch 6/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 322us/step - loss: 0.3237 - val_loss: 0.3968
Epoch 7/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 325us/step - loss: 0.3146 - val_loss: 0.4137
Epoch 8/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 325us/step - loss: 0.3042 - val_loss: 0.3534
Epoch 9/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 322us/step - loss: 0.2944 - val_loss: 0.3735
Epoch 10/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.2890 - val_loss: 0.3625
Epoch 11/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.2831 - val_loss: 0.3432
Epoch 12/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.2769 - val_loss: 0.3858
Epoch 13/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.2714 - val_loss: 0.3795
Epoch 14/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 324us/step - loss: 0.2672 - val_loss: 0.3833
Epoch 15/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.2614 - val_loss: 0.3808
Epoch 16/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.2582 - val_loss: 0.3748
Epoch 17/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.2536 - val_loss: 0.3566
Epoch 18/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.2517 - val_loss: 0.3600
Epoch 19/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 324us/step - loss: 0.2458 - val_loss: 0.3759
Epoch 20/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.2434 - val_loss: 0.3640
Epoch 21/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.2377 - val_loss: 0.3981
Epoch 22/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.2344 - val_loss: 0.4020
Epoch 23/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.2322 - val_loss: 0.3770
Epoch 24/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.2292 - val_loss: 0.3793
Epoch 25/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.2276 - val_loss: 0.3915
Epoch 26/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.2224 - val_loss: 0.3994
Epoch 27/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.2201 - val_loss: 0.3914
Epoch 28/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.2182 - val_loss: 0.3882
Epoch 29/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.2146 - val_loss: 0.3867
Epoch 30/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.2156 - val_loss: 0.3944
Epoch 31/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 322us/step - loss: 0.2109 - val_loss: 0.3851
Epoch 32/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.2086 - val_loss: 0.3912
Epoch 33/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 322us/step - loss: 0.2083 - val_loss: 0.4032
Epoch 34/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.2049 - val_loss: 0.4402
Epoch 35/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.2017 - val_loss: 0.4044
Epoch 36/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 324us/step - loss: 0.1990 - val_loss: 0.4160
Epoch 37/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 324us/step - loss: 0.1988 - val_loss: 0.3954
Epoch 38/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 322us/step - loss: 0.1951 - val_loss: 0.4143
Epoch 39/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.1937 - val_loss: 0.4467
Epoch 40/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.1928 - val_loss: 0.4176
Epoch 41/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.1911 - val_loss: 0.4121
Epoch 42/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 329us/step - loss: 0.1885 - val_loss: 0.4341
Epoch 43/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.1885 - val_loss: 0.4442
Epoch 44/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 322us/step - loss: 0.1850 - val_loss: 0.4754
Epoch 45/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.1835 - val_loss: 0.4530
Epoch 46/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.1835 - val_loss: 0.4381
Epoch 47/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.1828 - val_loss: 0.4471
Epoch 48/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.1786 - val_loss: 0.4555
Epoch 49/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 323us/step - loss: 0.1773 - val_loss: 0.4739
Epoch 50/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 325us/step - loss: 0.1797 - val_loss: 0.4582
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 220us/step - loss: 0.4207
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 214us/step
Epoch 1/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 368us/step - loss: 0.5716 - val_loss: 0.4350
Epoch 2/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 321us/step - loss: 0.4041 - val_loss: 0.4001
Epoch 3/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 321us/step - loss: 0.3706 - val_loss: 0.3832
Epoch 4/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 321us/step - loss: 0.3524 - val_loss: 0.3802
Epoch 5/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.3370 - val_loss: 0.4023
Epoch 6/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 321us/step - loss: 0.3250 - val_loss: 0.3784
Epoch 7/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 321us/step - loss: 0.3191 - val_loss: 0.3664
Epoch 8/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.3046 - val_loss: 0.3741
Epoch 9/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.3003 - val_loss: 0.3583
Epoch 10/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.2940 - val_loss: 0.3592
Epoch 11/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.2859 - val_loss: 0.3392
Epoch 12/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.2829 - val_loss: 0.3560
Epoch 13/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 319us/step - loss: 0.2742 - val_loss: 0.3552
Epoch 14/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 319us/step - loss: 0.2718 - val_loss: 0.3426
Epoch 15/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 319us/step - loss: 0.2646 - val_loss: 0.3529
Epoch 16/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 319us/step - loss: 0.2634 - val_loss: 0.3706
Epoch 17/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 319us/step - loss: 0.2581 - val_loss: 0.3468
Epoch 18/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 322us/step - loss: 0.2540 - val_loss: 0.3488
Epoch 19/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 321us/step - loss: 0.2509 - val_loss: 0.3568
Epoch 20/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.2481 - val_loss: 0.3653
Epoch 21/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.2445 - val_loss: 0.3775
Epoch 22/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 321us/step - loss: 0.2418 - val_loss: 0.3524
Epoch 23/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.2398 - val_loss: 0.3603
Epoch 24/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.2364 - val_loss: 0.3581
Epoch 25/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.2329 - val_loss: 0.3589
Epoch 26/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.2307 - val_loss: 0.3581
Epoch 27/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.2292 - val_loss: 0.3552
Epoch 28/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 319us/step - loss: 0.2268 - val_loss: 0.3770
Epoch 29/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 319us/step - loss: 0.2226 - val_loss: 0.3738
Epoch 30/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.2213 - val_loss: 0.3804
Epoch 31/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.2179 - val_loss: 0.3878
Epoch 32/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.2150 - val_loss: 0.3829
Epoch 33/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.2151 - val_loss: 0.3747
Epoch 34/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 319us/step - loss: 0.2116 - val_loss: 0.3920
Epoch 35/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.2103 - val_loss: 0.3859
Epoch 36/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.2064 - val_loss: 0.3859
Epoch 37/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.2076 - val_loss: 0.3727
Epoch 38/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 319us/step - loss: 0.2037 - val_loss: 0.4069
Epoch 39/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 319us/step - loss: 0.2011 - val_loss: 0.3979
Epoch 40/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.2012 - val_loss: 0.4165
Epoch 41/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.2036 - val_loss: 0.3938
Epoch 42/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.1988 - val_loss: 0.4093
Epoch 43/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 319us/step - loss: 0.1968 - val_loss: 0.4022
Epoch 44/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.1958 - val_loss: 0.4150
Epoch 45/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 321us/step - loss: 0.1920 - val_loss: 0.4141
Epoch 46/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 319us/step - loss: 0.1922 - val_loss: 0.4357
Epoch 47/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.1912 - val_loss: 0.4135
Epoch 48/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.1904 - val_loss: 0.4382
Epoch 49/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 319us/step - loss: 0.1871 - val_loss: 0.4304
Epoch 50/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.1866 - val_loss: 0.4399
Epoch 51/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.1864 - val_loss: 0.4214
Epoch 52/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.1866 - val_loss: 0.4424
Epoch 53/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.1807 - val_loss: 0.4424
Epoch 54/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 319us/step - loss: 0.1816 - val_loss: 0.4377
Epoch 55/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 319us/step - loss: 0.1821 - val_loss: 0.4399
Epoch 56/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.1771 - val_loss: 0.4438
Epoch 57/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.1780 - val_loss: 0.4597
Epoch 58/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.1802 - val_loss: 0.4656
Epoch 59/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 320us/step - loss: 0.1771 - val_loss: 0.4631
Epoch 60/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 319us/step - loss: 0.1744 - val_loss: 0.4849
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 219us/step - loss: 0.4726
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 210us/step
Epoch 1/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 360us/step - loss: 0.5704 - val_loss: 0.4552
Epoch 2/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 317us/step - loss: 0.4161 - val_loss: 0.4121
Epoch 3/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.3824 - val_loss: 0.3909
Epoch 4/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 319us/step - loss: 0.3603 - val_loss: 0.3881
Epoch 5/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.3400 - val_loss: 0.3604
Epoch 6/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.3300 - val_loss: 0.3880
Epoch 7/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.3168 - val_loss: 0.3768
Epoch 8/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 317us/step - loss: 0.3062 - val_loss: 0.3494
Epoch 9/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.2988 - val_loss: 0.3564
Epoch 10/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 317us/step - loss: 0.2911 - val_loss: 0.3452
Epoch 11/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 319us/step - loss: 0.2826 - val_loss: 0.3293
Epoch 12/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.2767 - val_loss: 0.3460
Epoch 13/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 317us/step - loss: 0.2717 - val_loss: 0.3539
Epoch 14/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.2671 - val_loss: 0.3513
Epoch 15/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.2612 - val_loss: 0.3472
Epoch 16/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 317us/step - loss: 0.2599 - val_loss: 0.3447
Epoch 17/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 317us/step - loss: 0.2529 - val_loss: 0.3450
Epoch 18/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.2504 - val_loss: 0.3499
Epoch 19/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 317us/step - loss: 0.2480 - val_loss: 0.3594
Epoch 20/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.2431 - val_loss: 0.3374
Epoch 21/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.2394 - val_loss: 0.3374
Epoch 22/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.2368 - val_loss: 0.3514
Epoch 23/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.2334 - val_loss: 0.3527
Epoch 24/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.2319 - val_loss: 0.3578
Epoch 25/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.2264 - val_loss: 0.3489
Epoch 26/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 317us/step - loss: 0.2271 - val_loss: 0.3649
Epoch 27/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.2218 - val_loss: 0.3560
Epoch 28/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.2215 - val_loss: 0.3548
Epoch 29/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 317us/step - loss: 0.2163 - val_loss: 0.3910
Epoch 30/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.2172 - val_loss: 0.3864
Epoch 31/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 317us/step - loss: 0.2140 - val_loss: 0.3718
Epoch 32/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 317us/step - loss: 0.2125 - val_loss: 0.3860
Epoch 33/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 317us/step - loss: 0.2089 - val_loss: 0.3707
Epoch 34/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.2080 - val_loss: 0.3835
Epoch 35/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 318us/step - loss: 0.2062 - val_loss: 0.3959
Epoch 36/70

In [29]:
all_precisions_B_df = pd.DataFrame(all_precisions_B)
all_precisions_B_df

         32        64        128       256       512
30  0.888070  0.891768  0.895320  0.897350  0.887000
40  0.879409  0.887228  0.898039  0.897341  0.900126
50  0.885017  0.894382  0.894854  0.901746  0.895220
60  0.877356  0.889529  0.894407  0.895990  0.897162
70  0.878638  0.887385  0.895871  0.894091  0.900960

##### POur ce model les meilleurs paramètres sont : nbre de neurones = 256 et epochs = 50. La précision est de 0.901746

### Model C

In [27]:
precisions_C = {}
all_precisions_C = {}

for neuron in neurons:
    for epoch in epochs:
        model_C = Sequential([
            Input(shape=(784,)),
            Rescaling(1./255),
            Dense(neuron, activation="relu"),
            Dense(10, activation="softmax")
        ])

        model_C.compile(optimizer=Adam(learning_rate=0.001), loss='categorical_crossentropy')

        model_C.fit(X_train, y_train_cat, epochs=epoch, batch_size=32, validation_split=0.1)

        model_C.evaluate(X_test, y_test_cat)

        y_predi_C = model_C.predict(X_test)

        y_pred_C = np.argmax(y_predi_C, axis=1)

        precisions_C[epoch] = precision_score(y_test, y_pred_C, average="macro")

    all_precisions_C[neuron] = precisions_C
    precisions_C = {}

Epoch 1/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 348us/step - loss: 0.5717 - val_loss: 0.4709
Epoch 2/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.4304 - val_loss: 0.4287
Epoch 3/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.3964 - val_loss: 0.4102
Epoch 4/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.3763 - val_loss: 0.4404
Epoch 5/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.3591 - val_loss: 0.3933
Epoch 6/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 302us/step - loss: 0.3462 - val_loss: 0.3852
Epoch 7/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.3350 - val_loss: 0.3849
Epoch 8/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.3260 - val_loss: 0.3868
Epoch 9/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 301us/step - loss: 0.3185 - val_loss: 0.3876
Epoch 10/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.3132 - val_loss: 0.3876
Epoch 11/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.3065 - val_loss: 0.3687
Epoch 12/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.2996 - val_loss: 0.3525
Epoch 13/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 302us/step - loss: 0.2951 - val_loss: 0.3605
Epoch 14/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 306us/step - loss: 0.2899 - val_loss: 0.3828
Epoch 15/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 306us/step - loss: 0.2870 - val_loss: 0.3592
Epoch 16/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 302us/step - loss: 0.2802 - val_loss: 0.3701
Epoch 17/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.2773 - val_loss: 0.3579
Epoch 18/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 301us/step - loss: 0.2732 - val_loss: 0.3554
Epoch 19/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 311us/step - loss: 0.2693 - val_loss: 0.3757
Epoch 20/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 301us/step - loss: 0.2661 - val_loss: 0.3673
Epoch 21/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 301us/step - loss: 0.2651 - val_loss: 0.3537
Epoch 22/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 301us/step - loss: 0.2613 - val_loss: 0.3576
Epoch 23/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.2574 - val_loss: 0.3743
Epoch 24/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.2558 - val_loss: 0.3671
Epoch 25/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 302us/step - loss: 0.2526 - val_loss: 0.3499
Epoch 26/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.2499 - val_loss: 0.3623
Epoch 27/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.2494 - val_loss: 0.3564
Epoch 28/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.2456 - val_loss: 0.3608
Epoch 29/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.2441 - val_loss: 0.3666
Epoch 30/30
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.2420 - val_loss: 0.3803
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 216us/step - loss: 0.3618
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 195us/step
Epoch 1/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 340us/step - loss: 0.5595 - val_loss: 0.4608
Epoch 2/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.4285 - val_loss: 0.4458
Epoch 3/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.3907 - val_loss: 0.3959
Epoch 4/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.3664 - val_loss: 0.3915
Epoch 5/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.3491 - val_loss: 0.3845
Epoch 6/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.3343 - val_loss: 0.3787
Epoch 7/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.3243 - val_loss: 0.3694
Epoch 8/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.3151 - val_loss: 0.3718
Epoch 9/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.3069 - val_loss: 0.3609
Epoch 10/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2996 - val_loss: 0.3646
Epoch 11/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2964 - val_loss: 0.3553
Epoch 12/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 296us/step - loss: 0.2852 - val_loss: 0.3612
Epoch 13/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 296us/step - loss: 0.2824 - val_loss: 0.3680
Epoch 14/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 296us/step - loss: 0.2769 - val_loss: 0.3849
Epoch 15/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2701 - val_loss: 0.3478
Epoch 16/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2659 - val_loss: 0.3440
Epoch 17/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2637 - val_loss: 0.3397
Epoch 18/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2612 - val_loss: 0.3419
Epoch 19/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2575 - val_loss: 0.3774
Epoch 20/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 296us/step - loss: 0.2513 - val_loss: 0.3437
Epoch 21/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2488 - val_loss: 0.3839
Epoch 22/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2470 - val_loss: 0.3462
Epoch 23/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2421 - val_loss: 0.3548
Epoch 24/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2400 - val_loss: 0.3533
Epoch 25/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2377 - val_loss: 0.3490
Epoch 26/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2351 - val_loss: 0.3515
Epoch 27/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2334 - val_loss: 0.3634
Epoch 28/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 296us/step - loss: 0.2309 - val_loss: 0.3605
Epoch 29/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2276 - val_loss: 0.3566
Epoch 30/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2267 - val_loss: 0.3728
Epoch 31/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2238 - val_loss: 0.3664
Epoch 32/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 296us/step - loss: 0.2207 - val_loss: 0.3711
Epoch 33/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2180 - val_loss: 0.3587
Epoch 34/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2191 - val_loss: 0.3690
Epoch 35/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2157 - val_loss: 0.3696
Epoch 36/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2148 - val_loss: 0.3659
Epoch 37/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2123 - val_loss: 0.3661
Epoch 38/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2104 - val_loss: 0.3710
Epoch 39/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2112 - val_loss: 0.3964
Epoch 40/40
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2074 - val_loss: 0.3721
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 213us/step - loss: 0.3685
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 198us/step
Epoch 1/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 343us/step - loss: 0.5523 - val_loss: 0.4493
Epoch 2/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 301us/step - loss: 0.4188 - val_loss: 0.4394
Epoch 3/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.3806 - val_loss: 0.3991
Epoch 4/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.3626 - val_loss: 0.3847
Epoch 5/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.3459 - val_loss: 0.3635
Epoch 6/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.3356 - val_loss: 0.3822
Epoch 7/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.3246 - val_loss: 0.3679
Epoch 8/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.3161 - val_loss: 0.3523
Epoch 9/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.3097 - val_loss: 0.3533
Epoch 10/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.3039 - val_loss: 0.3720
Epoch 11/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.2961 - val_loss: 0.3673
Epoch 12/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.2914 - val_loss: 0.3556
Epoch 13/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.2882 - val_loss: 0.3457
Epoch 14/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.2798 - val_loss: 0.3361
Epoch 15/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.2751 - val_loss: 0.3453
Epoch 16/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.2719 - val_loss: 0.3416
Epoch 17/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.2673 - val_loss: 0.3469
Epoch 18/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.2634 - val_loss: 0.3503
Epoch 19/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.2586 - val_loss: 0.3561
Epoch 20/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.2556 - val_loss: 0.3502
Epoch 21/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.2519 - val_loss: 0.3988
Epoch 22/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.2502 - val_loss: 0.3877
Epoch 23/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.2454 - val_loss: 0.3693
Epoch 24/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.2420 - val_loss: 0.3634
Epoch 25/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.2400 - val_loss: 0.3637
Epoch 26/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.2366 - val_loss: 0.3709
Epoch 27/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.2356 - val_loss: 0.3726
Epoch 28/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.2333 - val_loss: 0.3729
Epoch 29/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.2292 - val_loss: 0.3712
Epoch 30/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.2280 - val_loss: 0.3830
Epoch 31/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.2235 - val_loss: 0.3977
Epoch 32/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.2235 - val_loss: 0.3815
Epoch 33/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.2208 - val_loss: 0.3820
Epoch 34/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.2193 - val_loss: 0.3781
Epoch 35/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.2170 - val_loss: 0.3851
Epoch 36/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.2132 - val_loss: 0.3805
Epoch 37/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.2120 - val_loss: 0.3877
Epoch 38/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.2103 - val_loss: 0.3849
Epoch 39/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.2087 - val_loss: 0.3872
Epoch 40/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.2058 - val_loss: 0.4056
Epoch 41/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.2077 - val_loss: 0.3961
Epoch 42/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.2034 - val_loss: 0.4167
Epoch 43/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.2013 - val_loss: 0.3865
Epoch 44/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.2011 - val_loss: 0.3999
Epoch 45/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.1990 - val_loss: 0.4081
Epoch 46/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.1980 - val_loss: 0.3915
Epoch 47/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.1966 - val_loss: 0.4227
Epoch 48/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.1949 - val_loss: 0.4210
Epoch 49/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.1932 - val_loss: 0.4153
Epoch 50/50
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.1919 - val_loss: 0.4146
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 213us/step - loss: 0.4009
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 196us/step
Epoch 1/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 338us/step - loss: 0.5572 - val_loss: 0.4807
Epoch 2/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 300us/step - loss: 0.4281 - val_loss: 0.4381
Epoch 3/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.3975 - val_loss: 0.4217
Epoch 4/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.3748 - val_loss: 0.4165
Epoch 5/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.3576 - val_loss: 0.3875
Epoch 6/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.3444 - val_loss: 0.3826
Epoch 7/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.3322 - val_loss: 0.3693
Epoch 8/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.3238 - val_loss: 0.3772
Epoch 9/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.3139 - val_loss: 0.3591
Epoch 10/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.3056 - val_loss: 0.3546
Epoch 11/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2963 - val_loss: 0.3423
Epoch 12/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.2917 - val_loss: 0.3598
Epoch 13/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.2866 - val_loss: 0.3415
Epoch 14/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2809 - val_loss: 0.3428
Epoch 15/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.2759 - val_loss: 0.3384
Epoch 16/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2712 - val_loss: 0.3489
Epoch 17/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2655 - val_loss: 0.3537
Epoch 18/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2633 - val_loss: 0.3487
Epoch 19/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2596 - val_loss: 0.3425
Epoch 20/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.2564 - val_loss: 0.3586
Epoch 21/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2517 - val_loss: 0.3422
Epoch 22/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2489 - val_loss: 0.3560
Epoch 23/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2461 - val_loss: 0.3443
Epoch 24/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.2448 - val_loss: 0.3693
Epoch 25/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2414 - val_loss: 0.3530
Epoch 26/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2383 - val_loss: 0.3558
Epoch 27/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.2367 - val_loss: 0.3522
Epoch 28/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2350 - val_loss: 0.3731
Epoch 29/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.2316 - val_loss: 0.3547
Epoch 30/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.2285 - val_loss: 0.3558
Epoch 31/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2290 - val_loss: 0.3828
Epoch 32/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2239 - val_loss: 0.3696
Epoch 33/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2242 - val_loss: 0.3642
Epoch 34/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2223 - val_loss: 0.3670
Epoch 35/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2204 - val_loss: 0.3743
Epoch 36/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2191 - val_loss: 0.3882
Epoch 37/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2172 - val_loss: 0.3838
Epoch 38/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2153 - val_loss: 0.3748
Epoch 39/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2125 - val_loss: 0.3917
Epoch 40/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2107 - val_loss: 0.3958
Epoch 41/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2101 - val_loss: 0.3928
Epoch 42/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2076 - val_loss: 0.4048
Epoch 43/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.2088 - val_loss: 0.4033
Epoch 44/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2069 - val_loss: 0.3874
Epoch 45/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2037 - val_loss: 0.4062
Epoch 46/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2011 - val_loss: 0.4028
Epoch 47/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2034 - val_loss: 0.4381
Epoch 48/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.1998 - val_loss: 0.4321
Epoch 49/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.1982 - val_loss: 0.4152
Epoch 50/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.1978 - val_loss: 0.4061
Epoch 51/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.1973 - val_loss: 0.4170
Epoch 52/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.1958 - val_loss: 0.4402
Epoch 53/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.1935 - val_loss: 0.4278
Epoch 54/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.1934 - val_loss: 0.4241
Epoch 55/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.1907 - val_loss: 0.4546
Epoch 56/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.1915 - val_loss: 0.4185
Epoch 57/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.1890 - val_loss: 0.4311
Epoch 58/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.1877 - val_loss: 0.4301
Epoch 59/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.1863 - val_loss: 0.4442
Epoch 60/60
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.1878 - val_loss: 0.4313
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 214us/step - loss: 0.4073
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 193us/step
Epoch 1/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 339us/step - loss: 0.5562 - val_loss: 0.4504
Epoch 2/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.4128 - val_loss: 0.4381
Epoch 3/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 296us/step - loss: 0.3771 - val_loss: 0.3836
Epoch 4/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.3566 - val_loss: 0.3708
Epoch 5/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.3400 - val_loss: 0.3775
Epoch 6/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.3292 - val_loss: 0.3647
Epoch 7/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 296us/step - loss: 0.3162 - val_loss: 0.3686
Epoch 8/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.3057 - val_loss: 0.3491
Epoch 9/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2996 - val_loss: 0.3588
Epoch 10/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2929 - val_loss: 0.3644
Epoch 11/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2848 - val_loss: 0.3473
Epoch 12/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2797 - val_loss: 0.3516
Epoch 13/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2741 - val_loss: 0.3550
Epoch 14/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2688 - val_loss: 0.3411
Epoch 15/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2642 - val_loss: 0.3463
Epoch 16/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 298us/step - loss: 0.2597 - val_loss: 0.3399
Epoch 17/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 296us/step - loss: 0.2561 - val_loss: 0.3513
Epoch 18/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2519 - val_loss: 0.3493
Epoch 19/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2473 - val_loss: 0.3883
Epoch 20/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 296us/step - loss: 0.2447 - val_loss: 0.3526
Epoch 21/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 296us/step - loss: 0.2413 - val_loss: 0.3390
Epoch 22/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 295us/step - loss: 0.2370 - val_loss: 0.3707
Epoch 23/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 296us/step - loss: 0.2367 - val_loss: 0.3721
Epoch 24/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2345 - val_loss: 0.3597
Epoch 25/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2314 - val_loss: 0.3777
Epoch 26/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2302 - val_loss: 0.3544
Epoch 27/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2257 - val_loss: 0.3547
Epoch 28/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 296us/step - loss: 0.2236 - val_loss: 0.3787
Epoch 29/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 295us/step - loss: 0.2226 - val_loss: 0.3686
Epoch 30/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 296us/step - loss: 0.2179 - val_loss: 0.3720
Epoch 31/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 299us/step - loss: 0.2187 - val_loss: 0.3625
Epoch 32/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2146 - val_loss: 0.3764
Epoch 33/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2149 - val_loss: 0.3779
Epoch 34/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 297us/step - loss: 0.2100 - val_loss: 0.3946
Epoch 35/70
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 1s 296us/step - loss: 0.2094 - val_loss: 0.3810
Epoch 36/70

In [30]:
all_precisions_C_df = pd.DataFrame(all_precisions_C)
all_precisions_C_df

         32        64        128       256       512
30  0.880956  0.887974  0.892689  0.895330  0.896895
40  0.882386  0.892490  0.897317  0.900927  0.897667
50  0.881086  0.884599  0.885706  0.895796  0.901690
60  0.884654  0.885383  0.893227  0.899019  0.892509
70  0.879187  0.879617  0.894920  0.896541  0.898153

##### POur ce model les meilleurs paramètres sont : nbre de neurones = 512 et epochs = 50. La précision est de 0.901690